# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  entrypoint: 'bash'
  args:
    - '-c'
    - >
      docker build
      --network=cloudbuild
      -t gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}
      -t gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest
      -f ./Dockerfile.gcp
      .

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest'

# Log bucket for storing build logs
logsBucket: ${_CLOUDBUILD_LOG_BUCKET} # Use substitution for bucket name
